version: '3.0'
services:
  proxy:
    build: .
    ports: 
    - "80:7357"

    depends_on:
    - reviews
    - reservations
    - description
    - mongo
  reviews:
    build: modules/FEC-Reviews-Component
    ports: 
    - "80:3002"

    depends_on:
    - mongo
  reservations:
    build: modules/FEC-Reservation-Component
    ports:
    - "80:3001"

    depends_on:
    - mongo
  description:
    build: modules/FEC-Description-Component
    ports:
    - "80:3000"

    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"