version: '3.0'
services:
  proxy:
    build: .
    ports: 
    - "80:80"

    depends_on:
    - description
    - reservation
    - reviews
  description:
    image: ertdfgcb/feccomponent
    expose:
    - "3000"
    depends_on:
    - mongo
  reservation:
    image: wpark95/fec
    expose:
    - "3001"
    depends_on:
    - mongo
  reviews:
    image: jzhengcode/fec-reviews-component_web
    expose:
    - "3002"
    depends_on:
    - mongo
  mongo:
    image: mongo:4.2.7
    expose:
    - "27017"